### ISSUE TITLE
About cropping videos of InternVid-G dataset during instruction tuning.

### ISSUE THREAD

**Issue by tiesanguaixia** [yellow-binary-tree/HawkEye#1]
感谢您精彩的工作和论文分享！我想问一下在使用InternVid-G数据集对VideoChat2进行instruction tuning时，您在论文4.2中讲到的crop the video的细节。我的理解是一个原始视频含有多个query, 每个query有与之匹配的原始边界，但是模型在这个query对应的那条训练数据中能看到的视频是被裁剪之后较短的一段。也就是说虽然数据集中的视频都是以完整视频的形式保存，但运行时模型能看到的视频都是原始视频的一个片段。这个理解是正确的吗？

**Comment by yellow-binary-tree** [comment]
是正确的
