### ISSUE TITLE
A naive question about training.

### ISSUE THREAD

**Issue by HenryHZY** [yellow-binary-tree/HawkEye#2]
Hi @yellow-binary-tree, thanks for your great project.

I am interested in reproducing the training & testing. Since "video downloading may take quite a while 🙃", could you please share how much storage space is needed to store videos? 

For example, 
> cd data/videos/
> du -h --max-depth=1

I think this information will help to smoothly download and store the data. Thank you very much:)

**Comment by HenryHZY** [comment]
By the way, as mentioned in the paper, "VideoChat2 (our impl., where the only difference with HawkEye is not introducing InternVid-G in instruction-tuning)".

Does this indicate that the only difference between VideoChat2 (our impl.) and VideoChat2 is that the former does not use the image-based dataset during the instruction tuning stage?

Also would like to know the training time cost of this ablation model and wonder if you could release its checkpoint of to HF for research usage:)

**Comment by yellow-binary-tree** [comment]
Thank you for your interest in this work!

We download all videos of the datasets (except Webvid). It will take a long time to get the accurate storage space for all 
 videos, but the approximate numbers are as follows:
- CLEVRER: **25GB**
- TGIF: **71GB**
- NExTQA: The zip files are **23GB**. Unzipped videos can be a bit larger.
- TextVR: The zip files are **115GB**. Unzipped videos can be a bit larger.
- YouCook2: **100GB**
- Kinetics: The zip files are 345GB (k400 train) + 604GB (k600 train) + 682GB (k700_2020 train) = **1631GB**. Unzipped videos can be a bit larger.
- SSv2: The zip files are **19GB**. Unzipped videos can be a bit larger.
- Charades: **16GB**
- WebVid: **508k videos** are used, and it takes **~800GB**
- InternVid-G: **83614 long (several minutes) videos** are used. The storage space required depends on the resolution of the videos you download. We downloaded 720p videos and it takes **~3TB**. But 224p videos are enough to reproduce HawkEye.

The training process of VideoChat2 (our impl.) takes 3.5 days on 8 V100 GPUs. We will release this checkpoint on Huggingface later.

The difference between VideoChat2 (our impl.) and VideoChat2 is:
1. not using the image-based instruction tuning dataset,
2. Freezing the Visual Encoder.

**Comment by HenryHZY** [comment]
> Thank you for your interest in this work!
> 
> We download all videos of the datasets (except Webvid). It will take a long time to get the accurate storage space for all videos, but the approximate numbers are as follows:
> 
> * CLEVRER: **25GB**
> * TGIF: **71GB**
> * NExTQA: The zip files are **23GB**. Unzipped videos can be a bit larger.
> * TextVR: The zip files are **115GB**. Unzipped videos can be a bit larger.
> * YouCook2: **100GB**
> * Kinetics: The zip files are 345GB (k400 train) + 604GB (k600 train) + 682GB (k700_2020 train) = **1631GB**. Unzipped videos can be a bit larger.
> * SSv2: The zip files are **19GB**. Unzipped videos can be a bit larger.
> * Charades: **16GB**
> * WebVid: **508k videos** are used, and it takes **~800GB**
> * InternVid-G: **83614 long (several minutes) videos** are used. The storage space required depends on the resolution of the videos you download. We downloaded 720p videos and it takes **~3TB**. But 224p videos are enough to reproduce HawkEye.
> 
> The training process of VideoChat2 (our impl.) takes 3.5 days on 8 V100 GPUs. We will release this checkpoint on Huggingface later.
> 
> The difference between VideoChat2 (our impl.) and VideoChat2 is:
> 
> 1. not using the image-based instruction tuning dataset,
> 2. Freezing the Visual Encoder.

Thank you very much for your detailed and prompt reply. They really help me a lot!!
