### ISSUE TITLE
About use CLIP to calculate the semantic similarity between each pair of adjacent scenes.

### ISSUE THREAD

**Issue by tiesanguaixia** [yellow-binary-tree/HawkEye#3]
May I ask how do you use CLIP to calculate the semantic similarity between each pair of adjacent scenes mentioned in `3.1 Dataset Construction` of your paper? And could you please provide the code used for Dataset Construction? Thanks a lot!

**Comment by yellow-binary-tree** [comment]
The dataset construction code is provided in `internvid_g/code`. The "CLIP to calculate the semantic similarity" part is in `internvid_g/code/clip_sim.py`.
