### ISSUE TITLE
What should the "folder" and "ckpt" be when testing the model's ability on video grounding?

### ISSUE THREAD

**Issue by tiesanguaixia** [yellow-binary-tree/HawkEye#4]
Hi, thank you for the favorable work! It seems like this [command](https://github.com/yellow-binary-tree/HawkEye/tree/main?tab=readme-ov-file#test-on-temporal-video-grounding-benchmarks-with-recursive-grounding) needs to specify the **folder** and **ckpt** to run the code:
```
folder=$1
ckpt=$2
max_turns=4

# test on charades-sta
python tasks/test_recursive_grounding.py --max-turns ${max_turns} --config ${folder}/config.json \
    --ckpt ${folder}/ckpt_${ckpt}.pth \
    --video-path data/videos/charades \
    --data-path data/test-anno/charades_sta-recursive_grounding.json \
    --save-path ${folder}/charades_sta-recursive_grounding-${ckpt}-${max_turns}_turns.jsonl \
    > ${folder}/charades_sta-recursive_grounding-${ckpt}-${max_turns}_turns.log 2>&1 &
wait
```
By the way, may I ask how to change the format of my own data so that the grounding performance of it can be tested? Now its format is like the [InterVid-G](https://huggingface.co/datasets/wangyueqian/InternVid-G) in jsonl. 

Looking forward to your reply! Thanks a lot!

**Comment by yellow-binary-tree** [comment]
During my training process, the HawkEye model is trained for 1000000 steps and the checkpoint is saved in `my_output_folder/ckpt_1000000.pth`. So when loading this checkpoint for testing, I can use `folder=my_output_folder` and `ckpt=1000000`. In your case, you can modify this script to make sure that the `--ckpt` parameter is the checkpoint file you want to load.
The `--save-path` and output redirect file `> xxx 2>&1` are just output files and you can specify any file name you want.

**Comment by yellow-binary-tree** [comment]
I have provided my test data in the [Google Drive](https://drive.google.com/file/d/1WVx_UGAnCmBIp8GgCpvtxHHenpYVur5u/view?usp=sharing) link in [the "Testing" section in the README](https://github.com/yellow-binary-tree/HawkEye?tab=readme-ov-file#testing). In `test-anno.zip` you can see files named `anetc-recursive_grounding.json`, `nextgqa-recursive_grounding.json` and `charades_sta-recursive_grounding.json`, these files show the input format of testing on grounding task.

**Comment by tiesanguaixia** [comment]
> I have provided my test data in the [Google Drive](https://drive.google.com/file/d/1WVx_UGAnCmBIp8GgCpvtxHHenpYVur5u/view?usp=sharing) link in [the "Testing" section in the README](https://github.com/yellow-binary-tree/HawkEye?tab=readme-ov-file#testing). In `test-anno.zip` you can see files named `anetc-recursive_grounding.json`, `nextgqa-recursive_grounding.json` and `charades_sta-recursive_grounding.json`, these files show the input format of testing on grounding task.

Thanks a lot! Did you provide the `--config ${folder}/config.json` file and `ckpt_1000000.pth`? How can I load them?

**Comment by yellow-binary-tree** [comment]
> Thanks a lot! Did you provide the `--config ${folder}/config.json` file and `ckpt_1000000.pth`? How can I load them?

This is provided at [https://huggingface.co/wangyueqian/HawkEye](https://huggingface.co/wangyueqian/HawkEye). The `.pth` file
 is identical to `hawkeye.pth`.

**Comment by tiesanguaixia** [comment]
> > Thanks a lot! Did you provide the `--config ${folder}/config.json` file and `ckpt_1000000.pth`? How can I load them?
> 
> This is provided at https://huggingface.co/wangyueqian/HawkEye. The `.pth` file is identical to `hawkeye.pth`.

Thanks a lot! By the way, could you provide some instructions on how to download the raw videos of Charades-STA? I am inference the grounding performance of HawkEye on my own dataset, the annotation format is correct but the code is always stuck when dealing with some videos and questions😢😢. I want to conduct the experiments on Charades-STA to check if there is some problem with my videos. Do you have any thoughts on this issue🌹🌹🌹
