### ISSUE TITLE
Question about NExT-GQA Evaluation

### ISSUE THREAD

**Issue by ShramanPramanick** [yellow-binary-tree/HawkEye#9]
Hi, Thanks for your work and open-sourcing the codebase. I have a question about how you calculate the score for NExT-GQA.

In the NExT-GQA test set, many samples have more than one ground-truth time window. However, your model outputs a single time window. How do you calculate the IoU score for such samples, when the number of gt time windows does not match with the number of predicted time windows? It would be also helpful if you kindly reflect which part of the code handles this. 

Thanks.

**Comment by yellow-binary-tree** [comment]
Thank you for your interest in this work!

To calculate grounding metrics for examples with more than 1 ground truth spans, we report the results based on the one with maximal overlap with the prediction, which follows the method used in the work that proposed the NExT-GQA benchmark (page 6 in [this paper](https://arxiv.org/abs/2309.01327)):

![image](https://github.com/user-attachments/assets/8452bfec-9783-4171-8445-f79b530500c6)

The code for this part is in `data_preparing/check_grounding_results.ipynb`, at the last line of the `check_ans` function:

```
def check_ans(pred_span, gold_spans):
    if not isinstance(gold_spans[0], (list, tuple)):
        gold_spans = [gold_spans]
    return max([calculate_iou(pred_span, gold_span) for gold_span in gold_spans])
```

**Comment by ShramanPramanick** [comment]
Thanks for providing the clarification, and giving reference to previous works!
